language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: osx
    osx_image: xcode10.2
before_install:
- eval "${MATRIX_EVAL}"
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # Install later python for compatability with cpp-coveralls
    export PYTHON=3.7.0;
    pyenv install ${PYTHON};
    export PYENV_VERSION=$PYTHON;
    export PATH="/Users/travis/.pyenv/shims:${PATH}";
  fi
- pip install --user cpp-coveralls
script:
- mkdir build
- cd build
- cmake -DCOVERAGE=1 -DVERILOGAST_BUILD_TESTS=ON ..
- cmake --build .
- ctest
- sudo make install
- "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then \n  test -f /usr/local/lib/libverilogAST.dylib
  \nelse \n  test -f /usr/local/lib/libverilogAST.so \nfi\n"
- test -f /usr/local/include/verilogAST.hpp
after_success:
- coveralls --root .. -E ".*CMakeFiles.*" -E ".*googletest-src.*" -E ".*tests/.*.cpp.*"
before_deploy:
- mkdir libverilogAST-release
- cd libverilogAST-release
- cmake -DCMAKE_BUILD_TYPE=Release ..
- cd ..
- tar -zcvf libverilogAST.tar.gz libverilogAST-release
deploy:
  provider: releases
  file: libverilogAST.tar.gz
  skip_cleanup: true
  on:
    repo: leonardt/verilogAST-cpp
    tags: true
    branch: master
  user: leonardt
  password:
    secure: kHU2TvMY4EVxi6wYMIOVMu+ziNSsuL+NLx2mCetufOwiClLh1KpBRsI+OzAReUZfVgdSCV5KtxNV9lmpDUYphT44AbRrtPMVeW/mw3mPMwYHGE9UJmFk6+cBLu7j8NBB97oeTrOnPbf+DxLxN6VUMqpBs/vHfTQuLpR5RdTUlgbnc2v5GZ0rWVqVDrMxnOyAgXEjjv7DL+CAlxZki2SwdiBeX7UzQZ22tB8ql4P1XCUtYzZTkED3knWLAb2eUFtkbjSRDjVZeKtEK8jz8Kdd1XsmYKYQfM4REtnrTWmxsQ54/8Ue0XArUVOuGVV4Pq8z+p/QpVaFxrzXjipaGI62w83GfEsd6BTOntTZxNm1xu5gXgkAPk0C+mghpxUt5BfqGA8wTS6krDJvRWBBjj8HJhluUBW6ehwXJQeRY3ysSNeFX8woc/bgWro91HbZdAziEIxTL7cw8NIIVSYLxwOe5p+l2DSzxdMeqnjB6mn3RWn9enz9i3qytxhXXclaQMg+7nvHHrOSCvlGVDwIuJK6cUzgfkknxwYDtzkdP8txAgQuzr0zDy4f6A7xHbhaMDPpAMy3v7EZ9T2/8tGi9bd7FYi1kzs/0FKyuz0DJiPwCMxDIkyEcaFn+Ua/ee66+nQtKhFl3YetBY9aaxdzMoBThH5V1tdfeA2C2D6fAr6v+SE=
