language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10.2


before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # Install later python for compatability with cpp-coveralls
      export PYTHON=3.7.0;
      pyenv install ${PYTHON};
      export PYENV_VERSION=$PYTHON;
      export PATH="/Users/travis/.pyenv/shims:${PATH}";
    fi
  - pip install --user cpp-coveralls


script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 -DVERILOGAST_BUILD_TESTS=ON ..
  - cmake --build .
  - ctest
  # Check that installation works
  - make install
  - test -f /usr/lib/libverilogAST.so
  - test -f /usr/include/verilogAST.hpp

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" -E ".*googletest-src.*" -E ".*tests/.*.cpp.*"
