language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: osx
    osx_image: xcode10.2
before_install:
- eval "${MATRIX_EVAL}"
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # Install later python for compatability with cpp-coveralls
    export PYTHON=3.7.0;
    pyenv install ${PYTHON};
    export PYENV_VERSION=$PYTHON;
    export PATH="/Users/travis/.pyenv/shims:${PATH}";
  fi
- pip install --user cpp-coveralls
script:
- mkdir build
- cd build
- cmake -DCOVERAGE=1 -DVERILOGAST_BUILD_TESTS=ON ..
- cmake --build .
- ctest
- sudo make install
- "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then \n  test -f /usr/local/lib/libverilogAST.dylib
  \nelse \n  test -f /usr/local/lib/libverilogAST.so \nfi\n"
- test -f /usr/local/include/verilogAST.hpp
after_success:
- coveralls --root .. -E ".*CMakeFiles.*" -E ".*googletest-src.*" -E ".*tests/.*.cpp.*"
before_deploy:
- mkdir libverilogAST-release
- cd libverilogAST-release
- cmake -DCMAKE_BUILD_TYPE=Release ..
- cd ..
- tar -zcvf libverilogAST.tar.gz libverilogAST-release
deploy:
  provider: releases
  api_key:
    secure: 06oMZdCiyHLrkwZ6RC6Lb+cueYXTfo+xJQvwHP+iTkrPsImF5MHN9ScsGR0oPZQFdAWcHeJ7flpX2nIx452FwDrbXwW04LDMR7etIphukiZP7o7BESRSrGwMz2XpwYXVb+PPf05GCbcQkW3lg748ZeFZ1r/4drTS4xWGDAdiEt+riI6a/hNtK58pleV+Bl11VLHcj2bIe7dBnWsdm6Au34q9MqILgJcPzejwWCCvMezgeYDmwb09KFns1aLaEQP1lg1Wk0LnUNUw02IMxkRkMgREUbiVOrQGnnWMDsuZaXNMYbMTSujhslnHUr9kq7Ej8yKRnkS7v0E4toaVxN56xgzEXfCBm3hXSz7TTVixqwQQbHw0YXNDsF/PXsKTiBEUKHhl2ngv05XbTqciy83vpBCXAVN6YzcANyVQYr+vWkM8icX5puSlsg4wMoXa8AvPtgLjvkumqB+HBCvCBACZK+XOPqtDQR9a+M/yRHTRd/8WxnrgJbqKFVdcOdU65l8j8rWFA4BzCGeCme2hfibA2Ca6umwn2hXRSrl7rOMyh3jfpOFlPOqKnTr3/AJZyyAxmVPgGExOfu8i7pg1V7ONr/Uqn0HFZf2eoKhrM8LE6ck38PYn+wUKE6RXvQE8HyypfaVFTWIiTwaP8TlwAu0mVfPuktRIhOxwyqfoC/obzGI=
  file: libverilogAST.tar.gz
  skip_cleanup: true
  on:
    repo: leonardt/verilogAST-cpp
    tags: true
    branch: master
