language: cpp
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: osx
    osx_image: xcode10.2
before_install:
- eval "${MATRIX_EVAL}"
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # Install later python for compatability with cpp-coveralls
    export PYTHON=3.7.0;
    pyenv install ${PYTHON};
    export PYENV_VERSION=$PYTHON;
    export PATH="/Users/travis/.pyenv/shims:${PATH}";
  fi
- pip install --user cpp-coveralls
script:
- mkdir build
- cd build
- cmake -DCOVERAGE=1 -DVERILOGAST_BUILD_TESTS=ON ..
- cmake --build .
- ctest
- sudo make install
- "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then \n  test -f /usr/local/lib/libverilogAST.dylib
  \nelse \n  test -f /usr/local/lib/libverilogAST.so \nfi\n"
- test -f /usr/local/include/verilogAST.hpp
after_success:
- coveralls --root .. -E ".*CMakeFiles.*" -E ".*googletest-src.*" -E ".*tests/.*.cpp.*"
before_deploy:
- mkdir libverilogAST-release
- cd libverilogAST-release
- cmake -DCMAKE_BUILD_TYPE=Release ..
- cd ..
- tar -zcvf libverilogAST.tar.gz libverilogAST-release
deploy:
  provider: releases
  api_key:
    secure: f34UuhVV1qfzkj2BY3pKXnjMGeQLsn23dvFStb97kLujSl+W37d57PCHlrQCTs99mzQOnR/OTF0O+DuQL5V4+K6ErEcQM19ta24aZsp/PxJur9QzySfEjwpb5+fq3hwh1g27ESEQ3MiX+wxZH5KPaNcGF9zXwRT+SCf4g50OwYkjfzibBiiwfyJ2M9ozAPXLQl+7b9zVMa+CHaDcTqfXIjQoUf3HV/6YHOpf8+AdgAGmUu8nI+NHT44+B93dnPqe2GU4y5wYiZAEwyQw13fiR1MfKiUYKkTdE7ZOs9RwxOO/ZgJkm2v1XY0LuUK9CLEJpnVM8h8V20ZdX9E4/RAwysMwyzxtqt0vMmuWIGiF9Xw1WZXvCBIdX53UOq28TFvtwwY5HrkuPibMbLSB40maD26MVHNJXaKhk2KltbMw+V+5iqMlMKaWzFGze+FenaDJlkbaf8cY+JSPl70BhoMbJ+4CIsZRJE7YIYNririb67W/c6O92Yd7dp+EhsnHnD5OtFmyvKyQZt0629uK0IRfvLw/QhCMn5B5UZzVHH56YI5u41yAZzl6B/tNMVrZopWE8LBURwXHFXmFLyu96Xji2VMz3ICAOOOmuJX9bImLMvpdLEye9oyE/ZRpihGeJ5Y6pPv0W2d5si8bHgkYfTzNoI4J8WqehiUXmcdDZ2/ZOAY=
  file: libverilogAST.tar.gz
  skip_cleanup: true
  on:
    repo: leonardt/verilogAST-cpp
    tags: true
    branch: master
